const REGISTER_A = 0
const REGISTER_F = 1
const REGISTER_BH = 2
const REGISTER_BL = 3
const REGISTER_CH = 4
const REGISTER_CL = 5
const REGISTER_X = 6
const REGISTER_SP = 7
const REGISTER_PC = 8

const REGISTERS = [
    REGISTER_A,
    REGISTER_F,
    REGISTER_BH,
    REGISTER_BL,
    REGISTER_CH,
    REGISTER_CL,
    REGISTER_X,
    REGISTER_SP,
    REGISTER_PC,
]

module.exports = {
    REGISTER_A,
    REGISTER_F,
    REGISTER_BH,
    REGISTER_BL,
    REGISTER_CH,
    REGISTER_CL,
    REGISTER_X,
    REGISTER_SP,
    REGISTER_PC,
    REGISTERS,
}